server:
  http_port: ":8080"

database:
  master:
    host: "db"
    port: "5432"
    user: "postgres"
    pass: ""
    name: "notifier"
    ssl_mode: "disable"

  slaves: []

  max_open_conns: 10
  max_idle_conns: 5
  conn_max_lifetime: 30m

retry:
  attempts: 3
  delay: 50ms
  backoff: 2.0

redis:
  address: "redis:6379"
  password: ""
  database: "0"