services:
  frontend:
    build:
      context: ./frontend
    container_name: shortener_frontend
    ports:
      - "3000:80"   # http://localhost:3000
    environment:
      - VITE_API_URL=http://shortener:8080
    depends_on:
      - shortener
    networks:
      - app-network

  shortener:
    build: ./backend
    command: ./url-shortener
    container_name: shortener
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
      migrator:
        condition: service_completed_successfully
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    env_file:
      - .env
    networks:
      - app-network

  migrator:
    image: kukymbr/goose-docker:3.24.2
    container_name: migrator
    command: up
    depends_on:
      db:
        condition: service_healthy
    environment:
      - GOOSE_DRIVER=${GOOSE_DRIVER}
      - GOOSE_DBSTRING=host=${DB_HOST} port=${DB_PORT} user=${DB_USER} password=${DB_PASSWORD} dbname=${DB_NAME}
      - GOOSE_MIGRATION_DIR=${GOOSE_MIGRATION_DIR}
    env_file:
      - .env
    healthcheck:
      test: [ "CMD", "sh", "-c", "exit 0" ]
      interval: 5s
      timeout: 3s
      retries: 1
    volumes:
      - ./backend/migrations:/migrations
    networks:
      - app-network

  db:
    image: postgres
    restart: always
    container_name: postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    env_file:
      - .env
    ports:
      - "5434:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "6380:6379"
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    command: [ "redis-server", "--requirepass", "${REDIS_PASSWORD}" ]
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network: